name: parallel test build
on: push
jobs:
  addTocart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run test:addToCart

      - name: Cypress test reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawsome report add to cart
          path: cypress/reports/html    



  registerPage-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run test:registerpage

      - name: Cypress test reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawsome report register page
          path: cypress/reports/html    